var num = 10;
var str = "Hello";
var bool = true;
var undef = undefined;
console.log("Number:", num);
console.log("String:", str);
console.log("Boolean:", bool);
console.log("Undefined:", undef);
var sum = num + 5;
console.log("Sum:", sum);
var greeting = str + " World!";
console.log("Greeting:", greeting);
var isTrue = bool && false;
console.log("Is True:", isTrue);
var test = undef;
console.log("Test:", test);
